
#TODO allow at least for a custom port

- name: test if liferay was installed
  stat:
    path: '{{ liferay__config }}'
  register: liferay_config

- name: fail if the installation is missing
  fail:
    msg: "Liferay was not installed correctly on {{ app__liferay__base }}"
  when: liferay_config.stat.isreg is not defined or not liferay_config.stat.isreg

- name: Gather the passwords file from the host itself.
  shell: 'cat {{ account_store }}'
  register: accountsfile

- name: Parse the file for passwords.
  set_fact: 'accountinfos={{ accountsfile.stdout | from_yaml }}'

- name: create a db user for the liferay db
  postgresql_user:
    name: '{{ app__liferay__db_user }}'
    password: '{{ accountinfos[liferay_db_credentails_name]["value"] }}'
  when:
    - postgresql__edit_db

- name: create a db for liferay
  postgresql_db:
    name: '{{ app__liferay__db_name }}'
    owner: '{{ app__liferay__db_user }}'
    encoding: UTF-8
    template: template0
  when:
    - postgresql__edit_db

- name: connect liferay to the newly created db
  blockinfile:
    create: yes
    dest: "{{ liferay__config }}"
    mode: 0600
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: DB"
    block: |
      jdbc.default.driverClassName=org.postgresql.Driver
      jdbc.default.url=jdbc:postgresql://localhost:5432/liferay
      jdbc.default.username={{ app__liferay__db_name }}
      jdbc.default.password={{ accountinfos[liferay_db_credentails_name]["value"] }}

- name: prepare an upgrade config, just in case
  blockinfile:
    create: yes
    dest: "{{ app__liferay__base }}/tools/portal-tools-db-upgrade-client/portal-upgrade-database.properties"
    mode: 0600
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: DB"
    block: |
      jdbc.default.driverClassName=org.postgresql.Driver
      jdbc.default.url=jdbc:postgresql://localhost:5432/liferay
      jdbc.default.username={{ app__liferay__db_name }}
      jdbc.default.password={{ accountinfos[liferay_db_credentails_name]["value"] }}
  when:
    - app__liferay__version_major >= '7.0'

